### ISSUE TITLE
Async Flask controller

### ISSUE THREAD

**Issue by alinaciuysal** [Starofall/OEDA#11]
[aiohttp](https://aiohttp.readthedocs.io/en/stable/) or [treq](https://crossbario.com/blog/Going-Asynchronous-from-Flask-to-Twisted-Klein/) can be integrated to the project for asynchronous processing in flask

**Comment by iliasger** [comment]
We are now using multithreading library so that each experiment runs on the backend in each own thread. This way, the callback for polling data for plotting should not interfere with the experiment execution. Check whether switching to multiprocesssing library (each experiment in each own process, not thread) is needed.
