### ISSUE TITLE
Some Log values are less than zero

### ISSUE THREAD

**Issue by alinaciuysal** [Starofall/OEDA#4]
When scale of data is changed from Normal to Log, some values appear to be less than zero. Proper handling or filtering is required for plotting the data as well as proper calculation of the initial threshold for smooth-line-chart.

**Comment by iliasger** [comment]
Since the visualization does not break, we can consider this a part of the target systems (in this case, CrowdNav) that we do not change because we do not control. 

BTW the reason for negative logs of overheads is that some overhead values are slightly less than one, due to some normalization operation on CrowdNav. Not an OEDA (and probably not even a CrowdNav issue) though.
